name: flutter_banking_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  drift_dev: ^2.28.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  fonts:
    - family: Roble
      fonts:
        - asset: assets/fonts/Roble.ttf
      
  assets:
    - assets/images/Kate.jpg
    - assets/images/Dave.jpg
    - assets/images/Jackie.jpg
    - assets/images/Tom.jpg
    - assets/images/Felca.jpg
    - assets/images/deel.jpg
    - assets/images/mastercard.jpg
    - assets/images/visa.jpg
    - assets/images/paypal.jpg