name: flutter_banking_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roble
      fonts:
        - asset: assets/fonts/Roble.ttf
      
  assets:
    - assets/images/Kate.jpg
    - assets/images/Dave.jpg
    - assets/images/Jackie.jpg
    - assets/images/Tom.jpg
    - assets/images/Felca.jpg
    - assets/images/deel.jpg
    - assets/images/mastercard.jpg
    - assets/images/visa.jpg
    - assets/images/paypal.jpg